service : test-deploy

plugins:
  - serverless-python-requirements
provider:
 name: aws
 runtime: python3.6
 region : us-east-1
 deploymentBucket:
  name : deploy-ml-tst
 iamRoleStatements:
  - Effect : Allow
    Action:
     - s3.GetObject
    Resource:
     - "arn:aws:s3:::deploy-ml-tst/*"

custom:
 pythonRequirements:
  slim : true

functions:
 lgbm-lambda:
  name: lgbm-lambda-function
  description : deploy trained lightgbm on aws lambda using serverless
  handler : main.lambda_handler
  events :
   - http : POST /predictadult